<a href="https://colab.research.google.com/github/RiccardoPallucchi/PytorchingAround/blob/master/Notes_1_(Pytorch).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
import numpy as np
a=tc.__version__
b=np.__version__
a,b

('1.4.0', '1.18.2')

In [0]:
#tensors:
a1=torch.tensor([[2,4,5],[6,3,7]], dtype=torch.int32)          #note: using 'tensor' I have to specify the values
a2=torch.zeros([2,3])                                          #note: using 'zeros', 'ones' or 'rand' I have to specify the dimension of the tensor
a3=torch.ones([3,5], dtype=torch.float64)
a4=torch.eye(4)                                                #identity matrix
a5=torch.rand((2,2))                                           #random numbers, range = [0,1]
a6=torch.randint(0,6,(4,5))                                    #random integer numbers, I must specify the range (in this case (0,6) )

a7=torch.rand((4,6))
a71=torch.ones_like(a7)                                        #create tensor having same shape of another tensor

t1=torch.rand([7,2], dtype=torch.float32)
n1=t1.numpy()                                                  #conversion torch-numpy

n2=np.random.rand(8,4).astype(np.int32)
t2=torch.from_numpy(n2)                                        #conversion numpy-torch

#properties of a tensor
a=torch.rand((5,6), dtype=torch.float64)
t,s,d=a.dtype, a.shape, a.device            #'device' tells me where the tensor resides: 'cpu'=RAM, 'cuda'=GPU; I can specify the device in the argument

In [0]:
#rank of a tensor: A scalar has rank 0, 1D-matrices (a vector) has rank 1, 2D-matrices (mxn) has rank 2, 3D-matrices (mxnxk) has rank 3, etc

T0=torch.tensor(3, dtype=torch.float32)                       #rank 0 tensor, it's a scalar
S=T0.item()                                                   #convert tensor to python base type
#print(T0, type(T0), '\n', S, type(S))

T1=torch.tensor([1,2,3], dtype=torch.int32)                   #rank 1 tensor: shape (n,), considered both row or column vector (it can be a scalar also)
T1_col=T1.reshape(1,-1)                                       #reshape
#print(T1_col, T1, sep='\n')

T2=torch.tensor([[1,2,3], [4,5,6]], dtype=torch.int32)        #rank 2 tensor: shape (n,m), it's a 2D matrix (T2) or a column vector (T2_2)
T2_2=torch.tensor([[1],[2],[3]])
T2_col=T2.reshape(-1,1)                                       #reshape to get a column vector
T2_col1=T2.reshape(1,-1)                                      #reshape to get a row vector
#print(T2,T2_col, T2_col1, sep='\n')

T3=torch.rand(3,6,7)                                          #rank 3 tensor: shape (k,m,n), it's a 3D matrix, a collection of k 2D Matrices (dim (m,n))
#print(T3)

In [0]:
#Transposing in 2 dimensions:
ap=torch.ones(5,2)
ap[4,-1]=19                                                    #I selected the 5th row (0,1,2,3,4) and the last column
pa=ap.transpose(1,0)                                           #two ways to transpose a tensor
pa2=torch.einsum('ij->ji', ap)
#print(ap,pa,pa2,sep='\n')

#in 3 dimensions:
up=torch.ones(2,5,3)
up[1,4,2]=42
pu=up.transpose(1,2)
pu2=torch.einsum('ijk->ikj', up)
#print(up, pu, pu2, sep='\n')

In [21]:
#reshaping a tensor:
help=torch.arange(18)
me=torch.arange(18).reshape(6,3)
fucking=torch.arange(18).reshape(3,2,3)
idiot=torch.arange(18).reshape(9,2)
#print(help, me, fucking, idiot, sep='\n')
idiot.reshape(-1,1)                                                  #reshape in a column vector
idiot.reshape(1,-1)                                                  #reshape in a row vector

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [0]:
#concatenation
worm1=torch.arange(12).reshape(3,4)
worm2=torch.arange(30,42).reshape(3,4)
TwoWorms=torch.stack((worm1,worm2),dim=0)                          #stack=unites two tensors on a new dimension (dim=0)
BiggerWorm=torch.cat((worm1,worm2), dim=0)                         #cat=unites two tensorson the first dimension (dim=0)
#print(TwoWorms, BiggerWorm, sep='\n')

In [0]:
#miscellaneous

torch.cuda.is_available()                                         #to check if a GPU is available ;(

from IPython.display import YouTubeVideo, HTML, display           #to import videos from YouTube
display(YouTubeVideo('gGn6ahUYkmY'))

try:                                                              #a nicer way to check an error (pay attention to the indentations)
  cookies=torch.arange(18).reshape(3,4)
except RuntimeError as e:
  print(e)

'''
soup                                                              #to comment more then a row
'''

In [69]:
#exercise 1: Matrix 3x3 (2 on diagonal, 1 elsewhere)
torch.ones(3,3)+torch.eye(3)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [75]:
#exercise 2: Given a matrix mxn, create another matrix of same shape filled with ones
X=torch.rand(5,8)
torch.ones_like(X)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
#exercise 3: Build a 4x4 tensor filled with zeros and the sequence (0,1,2,3) on the diagonal
a=torch.zeros([4,4])
index=torch.arange(4, dtype=torch.long)                #creates vector with values going from 'start' (0) to 'end' (4) , with 'step'=1
a[index,index]=index.to(torch.float)                   # '.to' to switch between types
a

tensor([[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 3.]])

In [0]:
#exercise 4: from tensor [0 to 9] to tensor [0,2,4,6,8],[1,3,5,7,9] using only reshape and transpose
gip=torch.arange(10)
pup=gip.reshape(5,2)
rap=pup.transpose(0,1)
torch.arange(10).reshape(5,2).transpose(0,1)             #all in one
#print(gip,pup,rap, sep='\n')

tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])

In [61]:
#exercise 4: from tensor 3x5x8x10 to tensor 10x8x3x5
sip=torch.rand((3,5,8,10))
sip2=sip.transpose(1,2).transpose(0,1).transpose(3,2).transpose(2,1).transpose(1,0)

sip3=torch.einsum('fghi->ihfg', sip)                                    #another way
torch.equal(sip2,sip3)
#print(sip2.shape)

True